### ISSUE TITLE
Conferences should show number of unassigned students

### ISSUE THREAD

**Issue by maxwolffe** [calblueprint/edge-yl#1167]
It might be helpful to add an additional panel (next to or within Statistic Information) that shows the number of students in the conference who are unassigned to a group, unassigned to a room, who still need to submit paperwork, etc (essentially just a way for volunteers to see a count of what still needs to be done for each conference)

**Comment by warrenshen** [comment]
@maxwolffe we need to think about this since right now we don't know which students belong to which conference without a group.

**Comment by maxwolffe** [comment]
@warrenshen Yeah, this is something that might make sense to ask them about. It seems like the most natural flow for them would be: 
Create Conference -> Import Students (by either adding them from the student pool, or creating them in the conference page) -> Create a bunch of groups (maybe just based on the number of students they have, maybe based on the number of volunteers they have) -> Create a bunch of rooms (based on the number of buildings they have) -> Assign students to rooms and groups.

**Comment by maxwolffe** [comment]
This would mean though that we'd have students who belong to a conference without going through a group. 0_0. 

We may want to ask Edge if a single student belong to more than one conference?

**Comment by maxwolffe** [comment]
Closed via 33249638dfe08c88f79019a7705225ad2c5e05e4
