### ISSUE TITLE
Add "Add students to rooms" Feature to conferences. 

### ISSUE THREAD

**Issue by maxwolffe** [calblueprint/edge-yl#1204]
This needs a little thought, but just like with the "Add students to groups" feature, we should be able to click on a button and assign students who aren't currently in rooms to open rooms. Students should only be assigned to rooms which have their gender, and according to edge we should avoid having students from the same group in the same room (this may be a little trickier). 

(Maybe there should be a modal that allows the user to specify some parameters... maybe this is also worth adding to the assignToGroups feature.)

**Comment by maxwolffe** [comment]
Maybe we can draw the flow for this feature out at the next work sesh @warrenshen

**Comment by warrenshen** [comment]
Sounds good!
