### ISSUE TITLE
Actually delete rooms when removed from a conference. 

### ISSUE THREAD

**Issue by maxwolffe** [calblueprint/edge-yl#1221]
Right now, we are simply setting the conference_id to nil in the room model when we click the x in the groups index. We lose all reference to these rooms once that's done. I think we should instead delete the rooms, but overwrite `before_destroy` in the room model to set each student's `room_id` to nil.

**Comment by akakitani** [comment]
dont worry guys i got this

**Comment by warrenshen** [comment]
LOL @akakitani ++
