### ISSUE TITLE
Consolidate EditModal and CreateModal

### ISSUE THREAD

**Issue by maxwolffe** [calblueprint/edge-yl#1275]
@warrenshen Not sure if this is actually true, but it looks to me that `CreateModal` and `EditModal` are pretty much the same (minus a single style difference). Does it make sense to consolidate them into an `OverlayModel` or something? Doesn't seem like a priority, but wanted to point it out before I forget.

**Comment by warrenshen** [comment]
@maxwolffe wouldn't be surprised if so - let's look into it in the near future.

**Comment by warrenshen** [comment]
Closing for now - we'll get back to this during refactor phase.
