### ISSUE TITLE
Include formatting hints to input questions through description column

### ISSUE THREAD

**Issue by maxwolffe** [calblueprint/edge-yl#1414]

**Comment by warrenshen** [comment]
If a `question` model is of `style` `input` or `textarea` and has a description, format it as such on the client!

Example (do something similar for phone number, email, and zip code fields):
<img width="172" alt="screen shot 2016-04-03 at 12 01 11 pm" src="https://cloud.githubusercontent.com/assets/8787796/14234278/eded2206-f993-11e5-8422-72ee0ad0bde6.png">
