### ISSUE TITLE
Create header search component

### ISSUE THREAD

**Issue by maxwolffe** [calblueprint/edge-yl#29]

**Comment by maxwolffe** [comment]
<img width="1680" alt="screen shot 2015-10-04 at 2 38 29 pm" src="https://cloud.githubusercontent.com/assets/3267539/10270430/e9ff2dce-6aa5-11e5-99d2-715b1c8346e8.png">

**Comment by warrenshen** [comment]
@anthonyhbh check out the image Max just attached above. He'll be making the search component but you can look at the image for a general idea on how to style the left and right sides of the header.

**Comment by anthonyhbh** [comment]
Got it!
