### ISSUE TITLE
Set up image uploading with carrier wave

### ISSUE THREAD

**Issue by warrenshen** [calblueprint/edge-yl#471]
https://github.com/carrierwaveuploader/carrierwave

**Comment by warrenshen** [comment]
@maxwolffe I'll let you take a jab at this - reach out to @charlesx2013 for guidance!

**Comment by charlesx2013** [comment]
nah

**Comment by maxwolffe** [comment]
nah

**Comment by maxwolffe** [comment]
IS this something we still want to do? I just started looking into it for TEDxBerkeley, and can start working on it again.

**Comment by warrenshen** [comment]
Yes, but not super high priority right now!

**Comment by charlesx2013** [comment]
Stop spamming my email guiz




On Fri, Feb 26, 2016 at 5:41 PM, Warren Shen <notifications@github.com>
wrote:

> Yes, but not super high priority right now!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/calblueprint/edge-yl/issues/471#issuecomment-189550730>
> .
>



-- 
Charles Xue
EECS | UC Berkeley Class of 2017
