### ISSUE TITLE
Dynamically render children of SidebarRecents 

### ISSUE THREAD

**Issue by anthonyhbh** [calblueprint/edge-yl#495]
Using conditional statements

student_page - use renderItems() and change route to the mapped attributes (Found in dropdown.es6.jsx)

**Comment by warrenshen** [comment]
```
          <Sidebar
            hidden={this.state.sidebar}
            profile={this.state.profile} />
```
in `StudentPage`.

**Comment by warrenshen** [comment]
`this.props.visits.map((visit, index) => this.renderItem(visit, index));`
