### ISSUE TITLE
Set up create a group feature from groups index page

### ISSUE THREAD

**Issue by warrenshen** [calblueprint/edge-yl#946]
For reference, check out how @unzunz set this up for the `RoomCreateModal`, which is rendered on both the `ConferencePage` and the `RoomsPage`.

**Comment by warrenshen** [comment]
Reassigned to @sonia-y , let me know if you started it already @maxwolffe !

**Comment by maxwolffe** [comment]
This is kind of a pre-req for #960, so I'm going to take it if that's coo.
